package Views

import UI.ChatMessage
import UI.CustomTextInput
import UI.TextInputOption
import UI.stringFlowRow
import Viewmodel.ChatsModel
import Viewmodel.WindowViewModel
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material.MaterialTheme
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ExitToApp
import androidx.compose.material.icons.automirrored.outlined.List
import androidx.compose.material.icons.filled.Settings
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import dev.langchain4j.agent.tool.JsonSchemaProperty.items
import dev.langchain4j.data.message.ChatMessageType
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

@OptIn(ExperimentalComposeUiApi::class)
@Composable
fun ChatView() {
    val scope = rememberCoroutineScope()
    val chat = remember { ChatsModel.instance }
    val window = WindowViewModel.instance

    var titleGenerated by remember { mutableStateOf(false) }
    var isGenerating by remember { mutableStateOf(false) }

    var showSettings by remember { mutableStateOf(false) }

    val windowTitle by window.windowTitle.collectAsState()

    val chatHistory by chat.currentChat.collectAsState()
    val followUpQuestions by chat.followUpQuestions.collectAsState()

    val listState = rememberLazyListState()

    LaunchedEffect(chatHistory) {
        if (chatHistory.filter { it.type() != ChatMessageType.SYSTEM }.size == 2 && !titleGenerated){
            chat.generateChatTitle {
                window.windowTitle.tryEmit(it)
            }
            titleGenerated = true
        }
    }

    LaunchedEffect(Unit){
        //chat.setSystemMessage("You are a rude Motherfucker and you responses are as unusefull as possible")
        //chat.setSystemMessage("Be as Polite as possible")
        chat.setSystemMessage("Be as Scientific and easy to understand as Possible.")
    }

    val leftButtonOptions = listOf<TextInputOption>(
        TextInputOption(Icons.AutoMirrored.Default.ExitToApp, "AI Respond") { chat.generateChat(){
            isGenerating = false
        } },
        TextInputOption(Icons.AutoMirrored.Outlined.List, "Generate Questions") { chat.generateFollowUpQuestions() },
        TextInputOption(Icons.Default.Settings, "Settings") { showSettings = !showSettings }
    )
    Box(modifier = Modifier.fillMaxSize().background(MaterialTheme.colors.background)) {

        LazyColumn(modifier = Modifier.align(Alignment.TopCenter).fillMaxWidth(), state = listState) {
            chatHistory.forEach { message ->
                item {
                    ChatMessage(modifier = Modifier.padding(top = 8.dp), message = message)
                }
            }
            item {
                Spacer(Modifier.size(300.dp))
            }
        }

        Column(Modifier.align(Alignment.BottomCenter).padding(8.dp)) {
            stringFlowRow(
                Modifier,
                followUpQuestions,
                onClick = {
                    isGenerating = true
                    chat.appendUserMessage(it)
                    chat.generateChat(onNewToken = {
                        scope.launch() {
                            isGenerating = true
                            listState.animateScrollToItem(chatHistory.size - 1)
                        }
                    }){
                        scope.launch {
                            delay(1000)
                            chat.generateFollowUpQuestions()
                            isGenerating = false
                        }
                    }
                    chat.clearFollowUpQuestion()
                }
            )
            CustomTextInput(
                Modifier,
                isLoading = isGenerating,
                rightButtonClick = { text ->
                    isGenerating = true
                    chat.appendUserMessage(text)
                    chat.generateChat(onNewToken = {

                        scope.launch() {
                            listState.animateScrollToItem(chatHistory.size - 1)
                        }
                    }){
                        scope.launch {
                            chat.generateFollowUpQuestions()
                            listState.animateScrollToItem(chatHistory.size - 1)
                            isGenerating = false
                        }
                    }
                },
                options = leftButtonOptions
            )
        }

        if(showSettings){
            SettingsView(Modifier.align(Alignment.Center), onBack = {
                showSettings = false
            })
        }
    }
}